version: '2'

labels:

    rocks.puffin.name: Rocket.Chat 
    rocks.puffin.subtitle: web chat platform 
    rocks.puffin.website: https://rocket.chat/ 
    rocks.puffin.description: |
        Rocket.Chat is the ultimate web chat platform.
        From group messages and video calls all the way to helpdesk killer features.

services:

    main:
        image: rocket.chat:latest
        depends_on:
            - db
        ports:
            - 3000
        volumes: 
            - main_data:/app/uploads
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
            - MAIL_URL=smtp://mail:25
        networks:
            - front
            - back
            - default

    db:
        image: loomchild/mongo
        volumes: 
            - db_data_db:/data/db
            - db_data_configdb:/data/configdb

volumes:
    main_data:
    db_data_db:
    db_data_configdb:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
