version: '2'

services:

    main:
        image: puffinrocks/rocketchat:latest
        depends_on:
            - db
        ports:
            - 3000
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
            - MAIL_URL=smtp://mail:25
            - ROOT_URL=http://${VIRTUAL_HOST}
        networks:
            - front
            - back
            - default
        volumes:
            - main_data:/app/uploads
        tmpfs:
            - /run
            - /tmp

    db:
        image: puffinrocks/mongo
        volumes: 
            - db_data_db:/data/db
            - db_data_configdb:/data/configdb

volumes:
    main_data:
    db_data_db:
    db_data_configdb:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
